### ISSUE TITLE
suppress console.error in nakadachi

### ISSUE THREAD

**Issue by rymizuki** [rymizuki/rym-lib#2]
```
2024-10-09T09:21:28+09:00
handle error NotOwnPassportException: user doesn't own a passport
2024-10-09T09:21:28+09:00
    at async /Users/mizuki_r/myproject/node_modules/@rym-lib/nakadachi/build/index.js:119:13
2024-10-09T09:21:28+09:00
    at async /Users/mizuki_r/myproject/build/index.js:202:43
2024-10-09T09:21:28+09:00
    at async Loader28.interact (/Users/mizuki_r/myproject/build/index.js:10287:5)
2024-10-09T09:21:28+09:00
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
2024-10-09T09:21:28+09:00
    at Service.verify (/Users/mizuki_r/myproject/build/index.js:3307:37)
```

**Comment by rymizuki** [comment]
not found console.error in nakadachi
